### ISSUE TITLE
Dual Monitor using IGPU

### ISSUE THREAD

**Issue by Vermilion-INK** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#1]
Hi,
I've done a setup using your configurations. It helped me a lot to make the setup very easily.
My setup is:
Core i9 10850k
Gigabyte Vision G

I'm trying to drive two monitors with my IGPU.
I have A BenQ 2K monitor and a Cintiq16 as a 2nd monitor plus drawing tab.
The device runs fine, but at startup while after apple logo loading almost half, the Cintiq16 turns black and after turning it off and on it works fine.
Can you suggest me anyway I can fix this?
Many thanks!

![Screenshot 2021-05-18 at 2 08 45 AM](https://user-images.githubusercontent.com/84350538/118550088-2174d800-b77e-11eb-9744-dced54cc7015.png)

**Comment by 5T33Z0** [comment]
I don't use the IGPU. I am using a discrete GPU. Try this framebuffer-patch: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/Additional%20Files/Intel%20UHD%20630_HDMI_DP_Framebuffer-Patch.plist

**Comment by Vermilion-INK** [comment]
Thank you! Your this patch already saved the day!

**Comment by pentium0** [comment]
> Thank you! Your this patch already saved the day!

So dual monitors with iGPU works?
Do we know what the limit is on 4k and refresh rate? Like, can we do a 4k 60hz on displayport and then a 2k 60hz on HDMI?
