### ISSUE TITLE
External Webcam supported on Big Sur with OpenCore?

### ISSUE THREAD

**Issue by arshak-kahnputers** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#11]
I have similar spec Hackintosh with OpenCore. Everything works apart from external webcam. Are you facing the same issue or is it functioning properly for you?

**Comment by 5T33Z0** [comment]
I have an HD920 C Logitech which works fine in Big Sur. Not tested in Monterey. You need proper USB port mappings, so the correct speed capabilities of the ports are applied. Otherwise everything defaults to USB 2.0 speeds.

**Comment by rursache** [comment]
@arshak-kahnputers USB Cameras work for me too (Catalina, Big Sur, Monteray), you just need proper USB Mapping

**Comment by arshak-kahnputers** [comment]
Actually it was properly mapped but it the webcam itself that had little to no support. I tried Logitech webcam and it works fine.
