### ISSUE TITLE
Excellent work, thank you very much for the effort

### ISSUE THREAD

**Issue by iofermento** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#14]
Thank you very much for the shared material, it helped me to improve things in my configuration, I appreciate it.

I have a doubt in the cpu power management guide. You recommend using iMac20.2 for i7/i9 and iMac20.1 for i5 when Dortonia recommends iMac20.1 for i7. Could you clear my doubts? Since I have an i7 10700, currently set to 20.1 but I saw some users using 20.2. I don't know if change to 20,2 or not.

**Comment by 5T33Z0** [comment]
imac20,1 Models: https://everymac.com/ultimate-mac-lookup/?search_keywords=iMac20,1
imac20,2 Models: https://everymac.com/ultimate-mac-lookup/?search_keywords=iMac20,2

As you can see, you can use both
