### ISSUE TITLE
Enable 4K Monitor

### ISSUE THREAD

**Issue by hmthang96** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#16]
I used your EFI and everything is OK else my 4K monitor. It doesn't show correctly resolution. 
I suggest you remove stolenmem and fbmem in framebuffer patch to enable 4K monitor. 2 options are only useful when you can't set memory higher than 32Mb.

**Comment by 5T33Z0** [comment]
This Framebuffer patch should be considered as a fallback if you don't have a dedicated Graphics Card. Since I don't have a 4K monitor I didn't know this.
