### ISSUE TITLE
WiFi not turning on after flashing the custom I225-V firmware

### ISSUE THREAD

**Issue by rursache** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#17]
Hello @5T33Z0,

I followed your great tutorial and flashed my I225-V with the custom firmware (I have the same motherboard, Vision G). Ethernet now works and it's great.
However my PCI-e Broadcom BCM94360CS2 card ([Fenvi HB1200](https://www.aliexpress.com/item/33031773766.html)) no longer works properly. Turning on WiFi is not doing anything. BT still works.

I can confirm that:
- I read both the [tutorial](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225-V_FIX.md) and the [stock vs custom firmware](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md) guides (including the ones on the [german forum](https://www.hackintosh-forum.de/forum/thread/56123-l%C3%B6sung-f%C3%BCr-i225-v-v2-problem-auf-z490-plattform-vornehmlich-gigabyte-boards-unte/) and [insanelymac](https://www.insanelymac.com/forum/topic/348493-discussion-intel-i225-v-on-macos-monterey/?do=findComment&comment=2782058))
- VT-d is enabled in BIOS
- I have `DisableIOMapper` disabled (in Kernel - Quirks)
- I do **not** have any DMAR or `.aml` files in either Add or Delete section of ACPI
- I do **not** have the `e1000=0` or `dk.e1000=0` boot-args
- I already reseted the NVRAM

Here is my EFI [config.plist](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/files/8746154/config.plist.zip)

Thanks for your guides and your help

**Comment by rursache** [comment]
With `DisableIOMapper` enabled macOS crashes after boot and using the DMAR files will make no difference to WiFi availability.

What else can I try?

**Comment by 5T33Z0** [comment]
Have you read this: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md

Which OS are ypu referring to?

**Comment by rursache** [comment]
I did read it, Monteray 12.3.1 (will update to 12.4) soon

**Comment by 5T33Z0** [comment]
Since I don't use wifi I can't help you for now. I suggest either reverting to stock firmware or asking someone in the thread at insanelymac or on reddit.

**Comment by 5T33Z0** [comment]
I can't check your config right now. I am on the road for a couple of days. The info in the table is based on reports made by other others of this board on the referenced insanelymac thread.

**Comment by rursache** [comment]
> Add SBUS-MCHC.aml and try again or use my EFI folder.

I added `SBUS-MCHC.aml` from your latest OC release, flashed the custom fw again but the WiFi still is not turning on

**Comment by 5T33Z0** [comment]
I can't help you with Wifi issues.

**Comment by rursache** [comment]
maybe leave the issue open so others can contribute or know there are drawbacks to flashing the custom fw?

**Comment by 5T33Z0** [comment]
From what I understand, you are not using my EFI and Config. So how's that supposed to be an issue of my EFI?  Might as well be an issue with your config and Wifi Card

**Comment by Stukz** [comment]
since I'm not so good at this I just copied @rursache EFI folder and I'm having the same issue, the Fenvi WiFi & Bluetooth works but on the other side ethernet won't. I don't want to take the risk of flashing, but just wanted to point that I have the same problem 😞 on the other side everything it's working as expected, so I decided to buy a PCI-Express Ethernet so I don't have to flash my board.

note: I have z490 vision G w/  I7 10700k

**Comment by rursache** [comment]
@Stukz this issue is about flashed boards. ethernet won't ever work without flashing the custom fw

**Comment by Stukz** [comment]
@rursache I don't feel confident on how to do it and also how to rollback in case I want the WiFi back 😔

**Comment by 5T33Z0** [comment]
@Stukz 

1. Test Wifi using my EFI folder
2. I don't use Wifi on this board and I won't - ever - so I can't test it.
3. There have been reports that Wifi works for them with the combinations of settings I explained here: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md
4. You can rollback the custom fw any time as explained in the flash guide: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225-V_FIX.md

**Comment by hmthang96** [comment]
> 

It is not related to custom fw. 
I flashed custom fw and use another efi and it worked both Ethernet (have to add e1000=0) and Wifi.
Maybe it related to aml files

**Comment by rursache** [comment]
@hmthang96 its weird tho, i'm using the aml files from @5T33Z0's EFI
