### ISSUE TITLE
Detect if you need to flash or not

### ISSUE THREAD

**Issue by vricosti** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#18]
Hi,
I have a Z490 Vision-D and I was curious to know if I could use I225-V on Monterey so before flashing anything I wanted to be able to save my current firmware and I have discovered that it might be possible to know if one need a flash or not.
I have downloaded [here](https://www.gigabyte.com/fr/Motherboard/Z490-VISION-D-rev-1x/support#support-dl-driver-lan) the 
Intel I225 Firmware Update Tool and uncompress on my desktop:
Then as an administrator you can run:

```
PS C:\Users\smart\OneDrive\Bureau\Nvmupdate145> .\i225\nvmupdatew64e.exe -i -l

Intel(R) Ethernet NVM Update Tool
NVMUpdate version 1.35.30.0
Copyright (C) 2013 - 2020 Intel Corporation.

Unsupported device found - DeviceId: 0D4D.
Inventory
[00:008:00:00]: Intel(R) Ethernet Controller (2) I225-V
        Flash inventory started.
        Shadow RAM inventory started.
        Shadow RAM inventory finished.
        Flash inventory finished.
[00:008:00:00]: Intel(R) Ethernet Controller (2) I225-V
        Vendor                 : 8086
        Device                 : 15F3
        Subvendor              : 1458
        Subdevice              : E000
        Revision               : 2
        LAN MAC                : 
        Alt MAC                : 
        SAN MAC                : 
        ETrackId               : 
        SerialNumber           : 
        NVM Version            : 1.69(1.45)
        PBA                    : G23456-000
        VPD status             : Not set
        VPD size               : 0
        NVM update             : No config file entry
          checksum             : Valid
```
So normally I would not need to flash but for the moment when I connect an ethernet cable it says connected but I cannot have access to internet and I don't get an ip from dhcp. 
It's even worst if I boot with the ethernet cable connected MacOS just freezes, Here is what I get in System report:

```
Bus:	PCI
  Vendor ID:	0x8086
  Device ID:	0x15f3
  Subsystem Vendor ID:	0x1458
  Subsystem ID:	0xe000
  Revision ID:	0x0002
  PCIe Link Speed:	5.0 GT/s
  PCIe Link Width:	x1
  Driver:	com.apple.DriverKit-AppleEthernetE1000
  BSD Device Name:	en1
  MAC Address:	b4:2e:99:fd:05:ef
  AVB Support:	No
```

**Comment by 5T33Z0** [comment]
Thanks for the commands. I will integrade it in my guide. But as far as I know, all Z490 Visiin G boards have this issue or at least the users I know who have this board. Maybe the Vision D uses a different hardware revisin of the rom which is not affected
