### ISSUE TITLE
PCIe Wifi Card (Fenvi T919) not recognised

### ISSUE THREAD

**Issue by MathieuUrstein** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#19]
Hello, first I'd like to thank you for your fantastic work. The EFI and documentations are excellent, and I was able to gain a lot of time with them.

I have the latest ([082.1](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/releases/tag/082.1)) EFI release of yours, here is my Hardware:

| Component | Details                                                       |
| :------------:|-------------------------------------------------------------- |
| **Board**     | Gigabyte Z490 Vision G |
| **CPU**       | Intel Core i9-10900KF                            |
| **RAM**       | G.Skill Trident Z Neo (2 x 16GB, DDR4-3600, DIMM 288 pin)                    |
| **GPU**       | Gigabyte Radeon RX 5700 XT Gaming OC                                 |
| **Audio**     | Realtek® ALC1220-VB                         |
| **Ethernet**  | Intel I225-V 2.5GbE |
| **Wifi**  | Fenvi T919 PCIe Card |

I have made everything work except for the wifi of my `Fenvi T919 PCIe` Card, which uses the `BCM94360` chipset. The Bluetooth of this card is working, though.

I have found this bit in the `config.plist` file:
```
<dict>
    <key>Comment</key>
    <string>DMAR replacement table for 3rd Party WiFi/Ethernet</string>
    <key>Enabled</key>
    <false/>
    <key>Path</key>
    <string>DMAR.aml</string>
</dict>
```

Which I enabled with no further success.

I'm stuck with a disabled Wifi panel, which I can't turn On:
![image](https://user-images.githubusercontent.com/3322861/173239339-d0a63cb4-87a5-4488-a667-e502da21fc31.png)

Any idea of what I may do wrong?

**Comment by 5T33Z0** [comment]
I am not using WiFi on this board, so I can't help you with that. For some users it works, for other's it doesn't

Please read this https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md

Also: _If_ you use the DMAR replacement table, _then_ you also have to use eneable the drop rule to drop the OEM DMAR tabe (in ACPI/delete)

**Comment by MathieuUrstein** [comment]
I'm using MacOS Big Sur `11.6.5` so I did the following:

```xml
<key>#PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)</key>
```
```xml
<string>I225-V Patch. Required tor macOS 10.15 up to 11.3 only!</string>
<key>Count</key>
<integer>1</integer>
<key>Enabled</key>
<false/>
```
```xml
<key>boot-args</key>
<string>dk.e1000=0 -allow_assetcache agdpmod=pikera</string>
```

I still have the stock firmware so to achieve this:
![image](https://user-images.githubusercontent.com/3322861/173254472-0e45d09e-cf5d-4cb2-8061-8f8c8844ed74.png)
![image](https://user-images.githubusercontent.com/3322861/173254444-fd6cd52b-4799-4539-bf20-972431291454.png)
I did the following:

```xml
<key>DisableIoMapper</key>
<false/>
```

Then I did the following which should be related to `DMAR dropped / replaced`
```xml
<string>Drop OEM DMAR Table</string>
<key>Enabled</key>
<true/>
```
```xml
<string>DMAR replacement table for 3rd Party WiFi/Ethernet</string>
<key>Enabled</key>
<true/>
```

I'm left with the `DMAR (OEM)` which I'm not sure what it refers to?

**Comment by 5T33Z0** [comment]
OEM = Original Equipment Manufacturer = the original, unmodified DMAR table. I think there's an error in my table, but this doesn't concern you, since you are using Big Sur

- Vt-D needs to be enabled in BIOS!
- DisableIOMapper = false
- Original DMAR droppend and replaced
- Disable the Booter and Kernel Patches for the VMM stuff: 
    - Skip Board ID check
    - Reroute HW_BID to OC_BID
    - Force IOGetVMMPresent
    - Reroute kern.hv_vmm_present patch (1)
    - Reroute kern.hv_vmm_present patch (2)
    - Disable Library Validation Enforcement
    - Catalina Patch can be disabled but doesn't matter really
- try without boot-arg dk.e1000=0

**Comment by MathieuUrstein** [comment]
Ok I tried pretty much everything combination and the following worked for me:

Vt-D: Enabled
DisableIoMapper: Enabled
DMAR (OEM): No
DMAR (dropped/replaced): Yes/Yes

With that I have `I225-V` and The PCIe Card working 👍
Thanks for your help.

**Comment by 5T33Z0** [comment]
Good to hear. But DisableIOMapper basically disables Vt-D in macOS so, you might as well turn Vt-D off.

**Comment by 5T33Z0** [comment]
@MathieuUrstein Can you please try with Vt-d disabled and report if it still works? Thanks.
