### ISSUE TITLE
SDT-RX580 

### ISSUE THREAD

**Issue by tommyw1979** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#21]
I cant seem to locate this file in the download and your github brings 404? thanks

**Comment by 5T33Z0** [comment]
The link is fixed. Thanks for letting me know. The SSDT is also included in the EFI (Release Section). I suggest using the DeviceProperties approach instead now. It's explained in the article the link points to.

**Comment by tommyw1979** [comment]
i have the same card as yours, what settings did you go for out interest? did you mod the fan speeds?

**Comment by 5T33Z0** [comment]
Check my OpenCore release there's a deviceproperty in the config. It's just disabled. Didn't mod the fan curve. I changed the BIOS switch to silent mode, no additional fan mods
