### ISSUE TITLE
I225-V

### ISSUE THREAD

**Issue by realmax44** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#22]
Hello
i tried your new  method with the sddt-i225v.aml and the AppleIntell210Ethernet.kext, but it don't work. I still don't get aconnction. The ssdt should change the subsystem-vendor-id to 1043, but it don't change anything. I don't dare to flash the i225-v, so tried this method for Monterey and Ventura. I've also opened a issue in @SchmockLord, because i've a Vision D, but the path for the i225-v is the same.

**Comment by 5T33Z0** [comment]
All I know on the matter documented on my repo. I can't help you further.

**Comment by realmax44** [comment]
But what could be the reason, that for example the subsystem-vendor-id don't chage to 1043 whe the ssdt is used. Does it change it on your side?

**Comment by 5T33Z0** [comment]
Verify the location of the I225 controller and adjust the ACPI path if necessary. On the Z490 Vison G it's: `_SB_.PCI0.RP02.D066`

My suggestion would be to discuss the issue with other users here: https://www.insanelymac.com/forum/topic/352281-intel-i225-v-on-ventura/

**Comment by realmax44** [comment]
On the Vision D it's the same path. Can you say if the ssdt changes the subsystem-vendor-id in your setup?

**Comment by 5T33Z0** [comment]
I have flashed the custom firmware months ago, so I can't tell.

**Comment by realmax44** [comment]
Regardless of this (flashed), the ssdt should change the value in your case, too. Would you please try and report?

**Comment by 5T33Z0** [comment]
I can't do that because the values which this SSDT changes are already fixed in the ROM so there's no chance for me to detect if it's working or not.

**Comment by realmax44** [comment]
I thought that flashing would change the system vendor-id to 1458, but the content of the ssdt says subsystem-vendor-id 1043, so if the ssdt works, it should change this value in your case, too.

**Comment by 5T33Z0** [comment]
And why don't you just change the ID to 1458 in SSDT then?

**Comment by realmax44** [comment]
Of course I've already tried this, too, but it doesn't change anything. It seems that the ssdt has no effect. That's the reason I ask you to try if the ssdt changes anything on your system.

**Comment by realmax44** [comment]
Did you try?

**Comment by realmax44** [comment]
Thanks for your help!

**Comment by 5T33Z0** [comment]
Patched ROM:
![nossdt](https://user-images.githubusercontent.com/76865553/181269666-eaf9fd68-a89d-4a1d-854a-9d0d7d36f48b.png)

SSDT:
![ssdt](https://user-images.githubusercontent.com/76865553/181269712-4eb78442-311f-4ee0-8c55-144b27ef4f29.png)

**Comment by realmax44** [comment]
Thank you! I've controlled erverything again after your last post but it didn't work for me. Then i put the ssdt from the last at the first place of the order in acpi of the config.plist and the values changed. I thought that the order of the acpi files don't matter but in this case it do so. But my problem with no connection is still persisting. Tried in Monterey and Ventura. I think ther's no way around flashing now.

**Comment by 5T33Z0** [comment]
Well, there _can_ be [dependencies in the sequences SSDTs are loaded](https://github.com/5T33Z0/OC-Little-Translated/tree/main/00_About_ACPI#ssdt-loading-sequence), but the injected values shouldn't change. No Idea why this is happening. Maybe it's related to the DTGP method it is using. Anyway, it's weird.

**Comment by realmax44** [comment]
Whe i say that the values changed i mean f. e. that the subsystem-vendor-id changed from 0x0000 to 0x1043 like it is on your second screenshot after applying the ssdt. I will the next days flash the i225-v, because it just don't connect with the ssdt.

**Comment by 5T33Z0** [comment]
Okay. Did you try delete the Network Prefs already?

`sudo rm /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist`
`sudo rm /Library/Preferences/SystemConfiguration/preferences.plist`

**Comment by realmax44** [comment]
No i didn't but i tried after you wrote that with the same result. No connection.

**Comment by realmax44** [comment]
I've read some more and now have activated AppleVTD with custom DMAR and dropping rule but still no succes with the ssdt. So i will flash when i come back from a short trip next monday.

**Comment by 5T33Z0** [comment]
Are you telling me you didn't read these instructions: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md#settings-combinations-stock-firmware before creating the issue?

**Comment by realmax44** [comment]
Surely i have, but tried without AppleVTD first but now i know that with or without AppleVTD it don't work for me with the ssdt method.

**Comment by 5T33Z0** [comment]
And what about `DisbaleIOMapper`?

**Comment by realmax44** [comment]
I put the ssdt-dmar.aml into acpi folder and in the config.plist. Then created the delete rule in acpi and disabled the quirk. AppleVTD is in ioregistryexplorer now.

**Comment by 5T33Z0** [comment]
Again: did you unselect `DisableIOMapper`

Using a modified DMAR table (did you modify it?) is only necessary in cases where you want to use the I225-V together with third party LAN/Wifi/BT cards because of some memory regions which are defined in the DMAR table which have to be removed.

But it's not a requirement in regards to getting AppleVTD to work. It should be present even without dropping/replacing the DMAR table but just by enabling VT-D it in the BIOS.

**Comment by realmax44** [comment]
I wrote that i disabled the quirk in my last answer and without custom created dmar and delete rule, my thunderbolt devices and my fenvi didn't work. I read about this before.

**Comment by 5T33Z0** [comment]
Well then there's nothing more I can do for you. Like I said in the beginning: all I know about the issue is documented in the files on my repo. There's nothing more for me to suggest or do.  

Please discuss the issue in the forum I mentioned with other users having this problem!

**Comment by realmax44** [comment]
I will flash the i225v on monday and i will report then.

**Comment by kokowski** [comment]
Sorry for the late response. Now i've flashed the i225-v with the mod an everything is working in Monterey and Ventura. So the ssdt-method didn't do the trick for me only flashing with activated applevtd did it.

**Comment by realmax44** [comment]
Hi and sorry for the late response. Now i have flashed the i225-v withe the mod and everything is working fine now with activated applevtd and dropping dmar rule. So i don't have any problems with wifi and thunderbolt devices. Unfortunately I have to say in conclusion that the ssdt-method don't work. Thanks for your work and time.
