### ISSUE TITLE
WiFi network card not recognized on default configuration

### ISSUE THREAD

**Issue by iofermento** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#23]
Hey, how are you doing? I have a doubt, if I set enabled to false in the following configuration like in your config.plist my network card is not recognized, but if I set enabled to true works without problem.

My network adapter is a envi `FV-T919` PCIe x1 802.11a/b/g/n/ac Wi-Fi Adapter `BCM94360CD`.

Keeps with your great work, no doubt the best Vision-G configuration ever 🔥 👍 

Your configuration
```
<dict>
	<key>All</key>
	<false/>
	<key>Comment</key>
	<string>Drop OEM DMAR Table</string>
	<key>Enabled</key>
	<false/>
	<key>OemTableId</key>
	<data></data>
	<key>TableLength</key>
	<integer>168</integer>
	<key>TableSignature</key>
	<data>RE1BUg==</data>
</dict>
```

My configuration
```
<dict>
	<key>All</key>
	<false/>
	<key>Comment</key>
	<string>Drop OEM DMAR Table</string>
	<key>Enabled</key>
	<true/>
	<key>OemTableId</key>
	<data></data>
	<key>TableLength</key>
	<integer>168</integer>
	<key>TableSignature</key>
	<data>RE1BUg==</data>
</dict>
```

**Comment by 5T33Z0** [comment]
Thanks. I DON'T use Wifi, that's why it's disabled.  That's why there's a README included with instructions on how to get the I225-V working depending  on the used macOS version as well as the used ROM (stock/patched)

I can only update the Instruction if I know the following: 

- macOS version
- stock or custom ROM for the I225-V
- Are I225-V AND Wifi/BT working _simultaneously_?

**Comment by trimal2** [comment]
Hello @5T33Z0 , thank you very much for your work.
My setup was working great with wifi only connection, until I had to use 1GB wired connection today.

I have the same issue with WiFi/BT `FV-T919` card.
• Monterey 12.5.1
• Stock ROM for the I225-V + fix Opt.1
• They are not working simultaneously. 
• iMac 20,1 smbios
I can confirm that Fenvi WIFI is not working if Drop OEM DMAR Table is disabled.

But I have tried all possible combinations and can't get I225-V to work:
`SSDT-I225V.aml` enabled or disabled
`Vt-D` on or off
`e1000=0` with and without
`Drop OEM DMAR Table` enabled or disabled
`DMAR (OEM)` enabled or disabled
`DisableIoMapper` enabled or disabled

I will make a dump of I225-V firmware right now to check.
Hopefully you can help me to make it work.
Please let me know if you will need any other info. Thanks.
