### ISSUE TITLE
(AppleMobileFileIntegrity) : failed to get local signing public key (e00002bc)

### ISSUE THREAD

**Issue by Terminalstrip** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#24]
Hello thanx for yout guides.
I have this error in my log, during boot is stop 5 seconds on this string

(AppleMobileFileIntegrity) <AppleMobileFileIntegrity`AMFIInitializeLocalSigningPublicKey()> AMFIInitializeLocalSigningPublicKey: failed to get local signing public key (e00002bc)

You know how to solve?

**Comment by 5T33Z0** [comment]
Don't use this repo for openming personal support requsts, please!

**Comment by Terminalstrip** [comment]
ok sorry

Il giorno gio 18 ago 2022 alle ore 16:38 5T33Z0 ***@***.***>
ha scritto:

**Comment by 5T33Z0** [comment]
No, it's okay, I had the wrong tab open at the time. I'll upload a new EFI later

**Comment by 5T33Z0** [comment]
@Terminalstrip New Release: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/releases/tag/084.2
