### ISSUE TITLE
z490 Vision D Port Map?

### ISSUE THREAD

**Issue by 0xCUB3** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#25]
I have this exact setup, except that I have a z490 vision D. Is there a port map available for that motherboard, or should I make it myself?

**Comment by 5T33Z0** [comment]
Look here: https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D
