### ISSUE TITLE
DRM Support

### ISSUE THREAD

**Issue by 0xCUB3** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#26]
Per [this article](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md#drm-compatibility-on-macos-11), DRM support isn't fully available for Macs using iGPUs (i.e. iMac20,2). Is there any workaround to get that fixed without using an iGPU-free SMBIOS?

**Comment by 5T33Z0** [comment]
Don't know. I use this system for media creation, not for consuming it.

**Comment by 0xCUB3** [comment]
> 

gotcha, ok.

**Comment by 5T33Z0** [comment]
Basically, any Browser which handles DRM via software can be used as a workaround: FIrefox, Chrome, tec.
