### ISSUE TITLE
USB Hard Disk in OC0.8.5

### ISSUE THREAD

**Issue by Qwenjin** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#27]
OC version: 0.8.5
problem: cannot identify external hard disk(SanDisk E61 1TB), but 0.8.4 is good.

![iShot_2022-11-01_10 00 08](https://user-images.githubusercontent.com/15087970/199142733-6148c211-c11b-459a-8247-b56b8db9aba1.jpg)

<img width="693" alt="image" src="https://user-images.githubusercontent.com/15087970/199142781-fcf36697-10a0-4c01-9060-282de1a93058.png">

**Comment by 5T33Z0** [comment]
Try a different USB port or map your own.

**Comment by Qwenjin** [comment]
My mainboard is Gigabyte Z490 Vision G too, other usb works but SanDiskE61 not

**Comment by Qwenjin** [comment]
`Drop OEM USB Port Map(xh_cmsd4)`  set `TableLength` from 14689 to 0.

**Comment by 5T33Z0** [comment]
You MUST drop this table. Otherwise the replacement USB Port Map SSDT-PORTS does not work and the port types and speeds will not be correct.

If you don't drop this table you need to create your own USB Ports kext!
