### ISSUE TITLE
Ventura

### ISSUE THREAD

**Issue by goldiiii** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#28]
Moin, 

bin Toto ausm hackintosh Forum. Hatte da meine EFI gepostet die mit BigSur läuft. (Da hattest du kommentiert als Gast)

Ich versuche aktuell auf Ventura zu wechseln und das mit deinen Dateien, bis jetzt leider ohne Erfolg. Bricht während der Installation immer ab.

Hast du das schon hinbekommen? Sehe nur was von Beta bei dir.

Würde mich sehr freuen, wenn du dich evtl im Hackintosh Forum nicht nur als Gast anmelden würdest :) Dann könnte ich dich da kontaktieren. Lieben Gruß und Danke, dass du die Config auch teilst.

LG Goldi (Toto)

**Comment by 5T33Z0** [comment]
Hallo.

Ventura läuft bei mir schon sehr lange. 13.1 ist halt die neuste beta. Mehr als die Instruktionen in der Repo, der  Dokumentation im Readme und im Changelog die der .zip datei beiliegen kann ich nicht anbieten. Zum Hackintosh-Forum werde ich nicht zurückkehren. 

Viel Erfolg.
