### ISSUE TITLE
side Issue with intel wifi

### ISSUE THREAD

**Issue by vincerutabaga** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#29]
I have a Z490 AORUS PRO AX motherboard with this NIC.
I flash the rom as explained, work perfectly for me, without the boot arg "e1000=0".
The driver loaded is "com.apple.DriverKit-AppleEthernetE1000". Card is detected as Intel(R) I225 V.
DisableIoMapper quirk is set to disable, and with this I am able to use TB2 to RJ45 adaptor (with TB3 to TB2), it was not working before.
But for some reason that same quirk disable wifi with the onboard intel AX201. In the log :
Driver "itlwm" needs "IOPCITunnelCompatible" key in plist

**Comment by 5T33Z0** [comment]
I have no experience with Intel Wifi. I'd suggest you open a support request on the OpenIntelFireless Github.

**Comment by vincerutabaga** [comment]
After looking into it, the solution is to drop/delete oem DMAR table and replace it with a custom DMAR SSDT, with the reserved regions deleted!

**Comment by 5T33Z0** [comment]
Okay. Thanks for the info. Which macOS version are you using? Then I can update the instructions.

**Comment by vincerutabaga** [comment]
Use Monterey 12.6.1
And It work without ssdt-DMAC
Thanks for your tutorial
If I go to Ventura later, I will just have to add the intel kext ?

**Comment by vincerutabaga** [comment]
Yes I know about that, I will wait until the os is stable to switch anyway.
I was asking about "AppleIntelI210Ethernet.kext".  Is it needed for the I225 NIC ?

**Comment by 5T33Z0** [comment]
You said you flased the custom ROM, so no.
