### ISSUE TITLE
Sleep Issues?

### ISSUE THREAD

**Issue by prabs77** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#31]
Thank you for the great work on this. Everything seems to work straight out the box, except I have sleep issues. Can you share your pmset settings?

**Comment by 5T33Z0** [comment]
Sleep issue can be related to the SMBIOS and also to CPU friend. Did you generate your own CpuFriendDataProvider kext?

I haven't changes an pmset parameters. Since I use this system for work only, it never sleeps. It's either on or off.

**Comment by prabs77** [comment]
Using iMac 20.1. And I did generate my own Cpu Friend data. 

This is my current pmset

System-wide power settings:
Currently in use:
 standby              1
 Sleep On Power Button 1
 womp                 1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             1
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                1 (sleep prevented by sharingd, coreaudiod)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         20
 tcpkeepalive         1
 highstandbythreshold 50
 standbydelaylow      86400

**Comment by 5T33Z0** [comment]
run `pmset -g` to see recent wake reasons.

My suggestions:

- Disable PowerNap
- Disable ProximityWake `sudo pmset proximitywake 0`

**Comment by 5T33Z0** [comment]
Currently, my system won't enter sleep when idle since spotlight is indexing the drive in macOS Ventura. But sending it to sleep via the Apple menu works fine. It's something I don't really care about, so I won't invest any time looking into.

But if you find a solution, you can let it be known here.
