### ISSUE TITLE
USB 3.2 on Vision-G

### ISSUE THREAD

**Issue by bt** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#34]
Hi there,

First and foremost, thank you so much for this repo. Very great work!

I wanted to ask, have you been able to achieve USB 3.2 speeds on the Vision G Z490?

According to "About This Mac", it's only finding a USB 3.1 hub and maxing speeds at 5Gbit, even for USB3.2 devices. So I'm looking to see if it's a limitation of macOS or if I have an incorrect configuration.

**Comment by 5T33Z0** [comment]
USB 3.2 (or USB 3.1 Gen 2 as it's called also) is not supported by macOS. Apple uses Thunderbold 3 for that. So no, you don't have an incorrect configuration. In this case you need to use Windows or get a Thunderbold card, which requires a modded firmware to work with macOS.
