### ISSUE TITLE
metal 3 and igpu dgpu share the same slot

### ISSUE THREAD

**Issue by juliu1515** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#35]
Hi I have been using your build for 2 years now. Your job here is great ! 
I have an I9 10900k z490 vision G and I just replaced my rx 570 with a 6800 xt yesterday, I am on imac 20,2. I have added and activated kext for the power supply table DAGPM.kext and the SSDT-NAVI.aml. The card loads fine now. Monterney 12.6.3. I am changing for big sur or Ventura tomorrow because I got the mds_stores cpu full charge problem on every boot.
I am currently trying to activate metal 3. I have added the slot-name for iGPU and GPU with oca in DP, I finally have the 2 gpu's showing up on activity monitor apparently. But they share the same slot like the conversation on insanelymac. I try my best but its always the same. However in my system report it still marks me metal 2 on the 6800xt and the metal script does not work , I have a funky error. 

My question is,  do you find a solution for slot issue could resolve it ? do you know if there any chance to have it working. 

Here my obscur error of the script. The accelarate script works and tell me everything is working. I update xcode ( Xcode: 13.4.1) because I was thinking is that but not giving chance for me. what xcode do you run. Last question if metal 3 is working for you  it is writing on system report > gpu > graphics/display > metal family. it write metal 2 for me.
I plan to try the 7.1 smbios tomorow but I hope fix before ...

The strange error
```
hansi-i10@iMac ~ % /Users/hansi-i10/Downloads/metalgpu ; exit;
dyld[1099]: Symbol not found: (_$sSS10FoundationE36_unconditionallyBridgeFromObjectiveCySSSo8NSStringCSgFZ)
  Referenced from: '/Users/hansi-i10/Downloads/metalgpu'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'
zsh: abort      /Users/hansi-i10/Downloads/metalgpu

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by juliu1515** [comment]
Oh , right SSDT-NAVI not necessary, I had a black screen at startup with the correct boot arg however, that's why I had added them... I don't know what happened in the meantime. It's deleted. And it actually works.

Removing metal-enable makes the gpu tab disappear. All the same.

So actually I have my card behind pci-brigde@0.
IODeviceTree:/PCI0@0/PEG1@1/PEGP@0/pci-bridge@0/GFX0@0

I followed the tutorial but with the 1 method I get stuck I'm a bit of a novice. I do not understand which ssdt of the system it is to drag in the terminal. I tried dragging the entire acpi folder. But refuses. I use the second method more simple for me. Add new ssdt-brg0 I change the path inside and its seems working. I dont know if good.

IODeviceTree:/PCI0@0/PEG1@1/PEGP@0/BRG0@0/GFX0@0 it is appear in IOservice now aswell. I suppose it's better now. Removing metal-enable still makes the gpu tab disappear. All the same.

I have 3 key in oca for my gpu, aapl with the corret patch, device_type and model, i desactivated hda-gfx onboard-2. it's still correct. I always feel it miss something. Can i try enable_metal here ? 

You still have rx 580 ? When i read all your documentary I was thinking you change sometime. I would like to know if metal 3 is active it should write on sys report. 

Well I will continue to turn around the scrip error. thx for help.

**Comment by juliu1515** [comment]
Double-click metalgpu to check Metal 3 support (macOS 13 only)

metal 3 support is for macos 13 that s why ...

**Comment by 5T33Z0** [comment]
[…]
> I followed the tutorial but with the 1 method I get stuck I'm a bit of a novice. I do not understand which ssdt of the system it is to drag in the terminal. I tried dragging the entire acpi folder. But refuses. I use the second method more simple for me. Add new ssdt-brg0 I change the path inside and its seems working. I dont know if good.

Well, the guide says: "drag in your system's **D S D T** and hit Enter".

If it works then it's good!

`metalgpu` is for testing if metal 3 is supported and working for either iGPU or GPU. You either enable Metal 3 for the iGPU or the GPU – not both.
