### ISSUE TITLE
Broken download link for AppleIntel210Ethernet.kext (I225-V fix)

### ISSUE THREAD

**Issue by MaximPerry** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#36]
Hi, 
As per the [Intel I225-V Fix for macOS Monterey and newer](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225-V_FIX.md#option-1-using-a-ssdt-with-corrected-header-description) guide, I've been trying to get to download `AppleIntel210Ethernet.kext` as I'm trying to install MacOS Ventura but it brings us to an [Error 404 page](https://www.insanelymac.com/forum/topic/352281-intel-i225-v-on-ventura/?do=findComment&comment=2786214) even after login onto the web site. 

Anywhere else we could download `AppleIntel210Ethernet.kext`?

Btw, thanks for this awesome fix... looking promising!

**Comment by 5T33Z0** [comment]
Oh wow, so they deleted the whole thread… the link is fixed now.
