### ISSUE TITLE
You know this kext?

### ISSUE THREAD

**Issue by Terminalstrip** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#37]
[](url[)](https://github.com/SongXiaoXi/AppleIGC)

**Comment by 5T33Z0** [comment]
No, I don't. I will test it tomorrow. Thanks for pointing me to it!

**Comment by 5T33Z0** [comment]
Tested it in Ventura. It's loading and system settings says I'm connected via Ethernet. But I don't get a DHCP Lease so I can't reach any websites.
