### ISSUE TITLE
Flashing a custom firmware onto the EEPROM of the Intel I225-V Ethernet Controller

### ISSUE THREAD

**Issue by verdazil** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#38]
Hi, 5T33Z0!
I'm trying to flash a custom firmware onto the EEPROM of the Intel I225-V Ethernet Controller.
I use the firmware and tool recommended by the author. (I225MOD + eeupdate64e.efi)
Unfortunately, the file I225MOD is not flashed correctly and the adapter then does not work.

On the pictures in hex:
1. My original firmware
2. Author's modified firmware
3. My result after the firmware flashing

![picture-1](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/assets/88431749/21b3556a-1b7e-42f7-9eeb-dd146cc8494c)

What is the my error?

**Comment by 5T33Z0** [comment]
I don't know. It worked for me. But there's a kext now for the I225. Maybe it works for you:

https://github.com/SongXiaoXi/AppleIGC

**Comment by verdazil** [comment]
Thanks, I'll test!
Do I have to go back to stock firmware to use this kext? And what settings should I use?

**Comment by 5T33Z0** [comment]
I guess so. Becasue on my patched NIC, I didn't got a DHCP Lease with this kext. It connected to Ethernet but not to the Internet

**Comment by verdazil** [comment]
Yes thanks, it works now for me.
- stock firmware (Intel I225-V Ethernet Controller on Gigabyte-Z490-Vision-G)
- AppleIGC.kext used
- AppleIntelI210Ethernet.kext not used
- SSDT-I225V.aml not used
- boot-args e1000=0 used
- DisableIoMapper = YES (PlistEdit Pro)
- DisableIoMapperMapping = NO (PlistEdit Pro)

**Comment by 5T33Z0** [comment]
Great. Thanks for your report. I will add your settings to my article about fixing the i225-V!

**Comment by verdazil** [comment]
5T33Z0, really can work without **DisableIoMapper = YES**
I used this setting to work my WiFi+Bluetooth: Fenvi FV-T919 BCM94360CD

**Comment by 5T33Z0** [comment]
Can you show me a screenshot that verifies that this kext is actually serving th I225-V? It should be possible using IORegstryExplorer. That would be useful.

**Comment by 5T33Z0** [comment]
Thank you very much!
