### ISSUE TITLE
Reset flashed EEPROM to use AppleIGC?

### ISSUE THREAD

**Issue by mkschulze** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#39]
Hey,
I'm on the fence to upgrade to Sonoma, but I worry if I will be able to use ethernet. I previously had to flash my EEPROM to make ethernet work with Ventura. 

How would it be now if ethernet won't work in Sonoma. Do I have to flash back the original firmware and use that new AppleIGC.kext? Or can I use that kext also with a flashed EEPROM? Not sure I can find that original EEPROM. :/

**Comment by 5T33Z0** [comment]
Hey.
Ethernet works with the custom firmware. It's not necessary to revert the firmware. But it's still recommended to use AppleIGC for better performance. All you have to do is add the kext and enable the `DisableIOMapper`quirk. Check my latest EFI folder and changelog for reference.
