### ISSUE TITLE
about Intel(R) 1225-V

### ISSUE THREAD

**Issue by Qwenjin** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#4]
OpenCore Version: 0.7.2
os: Catalina 10.15.7

Intel(R) 1225-V Ethernet Controller is not working in Catalina(lastest, `19H1323`)， so I comment it in `DeviceProperties` and make it disabled in `Kernel -> Patch`
Fortunately, I use a dedicated network card(FVT919-BCM94360CD).

![image](https://user-images.githubusercontent.com/15087970/128469937-51dc20be-65b1-4b23-ace2-9a5d5664b668.png)

![image](https://user-images.githubusercontent.com/15087970/128471131-c59ac5bc-a4b6-4165-834a-63a0f5757691.png)

**Comment by 5T33Z0** [comment]
Follow instructions in the Readme.md to configure the Intel(r) I225-V Ethernet Controller for other macOS versions than macOS Big Sur 11.4 to get working internet.

**Comment by Qwenjin** [comment]
My previous OC config.plist(0.7.1)  refers to the instructions from Readme.md，but it can not boot since i upgrade Catalina to latest version. So I disable it in 0.7.2

**Comment by 5T33Z0** [comment]
Well, if you woukd have read the instructions thoroughly you would know that you need the kernel patch in Catalina as well as the device property.
