### ISSUE TITLE
Better sound Device Properties settings?

### ISSUE THREAD

**Issue by anzbanz** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#42]
Can I suggest a potential path for improving the sound settings in this bootloader? With the Display Properties present in this config file the sound settings experience certain issues. Namely, the output source switches to Builtin Headphones every time the system is reloaded. I fixed it using different device-id for audio in config file to 709D0000. It solved my situation in a way. As I'm using Loopback and Soundsource, these virtual sources work perfectly now. I can output my sound to the monitor source, the headphone source on my Elgato Wave XLR or if I connect external USB speakers they are also available as a source in the system. But there are no other sources that macOS usually has such as Builtin-Headphones, Builtin-Speakers etc. I do not care about those analog sources, which I never use anyways, as long as I have the other digital and virtual sources working well. 

Here is what the Device properties look like in the configure file.

<img width="983" alt="Screenshot 2024-07-17 at 21 24 40" src="https://github.com/user-attachments/assets/69ecf471-4802-4a00-a270-f6d0b0a1edb3">

**Comment by 5T33Z0** [comment]
I doubt that I will implement these DeviceProperties.  Simply because I don't use the on-board audio at all – I have an external audio interface since I produce music and sound design. And I don't want to test the on-board audio nor research that device-id you used.

But I may link to it in the repo's description.
