### ISSUE TITLE
thank you for the great EFI! cpu and fan sensors issue

### ISSUE THREAD

**Issue by pentium0** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#5]
hi 5T33Z0,

thank you for the excellent EFI. no problems whatsoever to report, but one feature request.

Include the virtualSMC plugin kexts (just SMCProcessor and SMCSuperIO?), and have them listed but disabled by default in config.plist
I added the kexts to the EFI folder and listed/enabled them in config.plist and all the sensors work normally.

**Comment by 5T33Z0** [comment]
Thanks for the feedback. I removed those plugin kexts because I recently found out they are unnecessary for monitoring temps and fan speeds. But I forgot to remove the entries fron the config as well. I will update the archive later.

**Comment by pentium0** [comment]
I'm interested in that...
They're not needed for monitoring sensors?
Even with iStat Menus? Before I installed the plugin kexts I was getting no sensors at all with iStat Menus

**Comment by 5T33Z0** [comment]
I am using hwmon smc 2 and Sometines intel power gadget. And in those, freqs, temps and fan speeds are displayed without thr extra sensors. Don't know about istat menus, though.
