### ISSUE TITLE
Hi,5T33Z0. The Intel i225-v compatible problem was solved!

### ISSUE THREAD

**Issue by guokai10000** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#6]
After I updated to the newest Monterey, the beta 7, the problem was solved.

**Comment by 5T33Z0** [comment]
GREAT! Thanks for the Info. I will update my system later!

**Comment by rursache** [comment]
FYI: i225-v only worked on Monteray beta 7, not working in any other beta or in the final release
